// todomvc-react/src/App.jsx
import React from 'react';

import TodoItem from "./components/TodoItem.jsx";

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      todos: JSON.parse(window.localStorage.getItem("react-todos") || "[]"),
      visibility: "all"
    };
  }

  // 添加todo
  addTodo = (e) => {
    if (e.keyCode != 13) {
      return;
    }
    let title = e.target.value;
    e.target.value = "";
    let arr = this.state.todos;
    arr.push({ id: Math.random() * 10, title: title, done: false });
    this.setState({
      todos: arr
    });
  }
  // 删除todo
  delTodo(id) {
    let arr = this.state.todos;
    arr.forEach((item, i) => {
      if (item.id == id) {
        arr.splice(i, 1);
      }
    })
    this.setState({
      todos: arr
    });
  }
  // 修改某一项的状态
  changeDone(id, checked) {
    let arr = this.state.todos;
    arr.forEach(item => {
      if (item.id == id) {
        item.done = checked;
        return;
      }
    });
    this.setState({
      todos: arr
    });
  }
  // 修改某一项的内容
  changeTitle(id, title) {
    let arr = this.state.todos;
    arr.forEach(item => {
      if (item.id == id) {
        item.title = title;
      }
    });
    this.setState({
      todos: arr
    });
  }
  // 全选或取消全选
  changeAllDone(e) {
    let arr = this.state.todos;
    arr.forEach(item => {
      item.done = e.target.checked;
    });
    this.setState({
      todos: arr
    })
  }
  // 遍历 todos,让 全选按钮 根据 todos 改变
  get allIsChecked() {
    return this.state.todos.every(item => item.done);
  }
  // 获取未完成的项数
  get noChecked() {
    return this.state.todos.filter(item => !item.done).length;
  }
  // 删除已经完成的项
  delAllDone = () => {
    let arr = this.state.todos.filter(item => !item.done);
    this.setState({
      todos: arr
    })
  }
  // 保存修改的内容
  saveEdit = (id, title) => {
    let arr = this.state.todos;
    arr.forEach(item => {
      if (item.id == id) {
        item.title = title;
        return
      }
    });
    this.setState({
      todos: arr
    })
  }
  // 点击对应的按钮显示对应的 列表 
  // all 显示所有
  // active 显示未完成的
  // completed 显示完成的

  // 设置 get 获取对应的列表
  get getList() {
    if (this.state.visibility == "all") {
      return this.state.todos;
    } else if (this.state.visibility == "active") {
      return this.state.todos.filter(item => !item.done);
    } else if (this.state.visibility == "completed") {
      return this.state.todos.filter(item => item.done);
    }
  }
  get todosLength() {
    return this.state.todos.length;
  }
  // 点击修改visibility显示对应的列表
  changeVisibility(val) {
    this.setState({
      visibility: val
    })
  }
  // 监听浏览器地址的变化
  hashChange = () => {
    const hash = window.location.hash.substr(2);
    if (hash == "") {
      this.setState({
        visibility: "all"
      });
    } else if (hash == "active") {
      this.setState({
        visibility: "active"
      });
    } else if (hash == "completed") {
      this.setState({
        visibility: "completed"
      });
    }
  }
  componentDidMount() {
    this.hashChange();
    window.onhashchange = this.hashChange;
  }
  componentDidUpdate() {
    window.localStorage.setItem("react-todos", JSON.stringify(this.state.todos));
  }


  render() {
    return <div>
      <section className="todoapp">
        <header className="header">
          <h1>react-todos</h1>
          <input className="new-todo" placeholder="What needs to be done?" onKeyUp={this.addTodo} />
        </header>

        <section className="main">
          <input id="toggle-all" className="toggle-all" checked={this.allIsChecked} type="checkbox" onChange={this.changeAllDone.bind(this)} />
          <label htmlFor="toggle-all">Mark all as complete</label>
          <ul className="todo-list">
            {this.getList.map((item, i) => {
              return <TodoItem {...item}
                key={i}
                changeDone={this.changeDone.bind(this)}
                delTodo={this.delTodo.bind(this)}
                changeTitle={this.changeTitle.bind(this)}
                saveEdit={this.saveEdit}
              ></TodoItem>
            })}
          </ul>
        </section>

        {
          // 条件判断,如果todos为空的话,状态栏也隐藏
          this.todosLength > 0 ?
            <footer className="footer" >
              <span className="todo-count"><strong>{this.noChecked}</strong> item left</span>
              <ul className="filters">
                <li>
                  <a className={this.state.visibility == "all" ? "selected" : null} onClick={this.changeVisibility.bind(this, "all")} href="#/">All</a>
                </li>
                <li>
                  <a className={this.state.visibility == "active" ? "selected" : null} href="#/active" onClick={this.changeVisibility.bind(this, "active")}>Active</a>
                </li>
                <li>
                  <a className={this.state.visibility == "completed" ? "selected" : null} href="#/completed" onClick={this.changeVisibility.bind(this, "completed")}>Completed</a>
                </li>
              </ul>
              <button className="clear-completed" onClick={this.delAllDone}>Clear completed</button>
            </footer>
            :
            null
        }
      </section>
    </div>
  }
}

// todomvc-vue+vuex/todomvc-vue/src/App.vue
<template>
  <div id="app">
    <!-- 1. 导入模板 -->
    <section class="todoapp">
			<header class="header">
				<h1>Vue-todos</h1>
				<input class="new-todo" @keyup.enter="addTodo($event)" placeholder="What needs to be done?" autofocus>
			</header>
			<!-- This section should be hidden by default and shown when there are todos -->
			<section class="main">
				<input id="toggle-all" class="toggle-all" type="checkbox" :checked="$store.getters.isAllCheck" @change="changeTodoState($event)">
				<label for="toggle-all">Mark all as complete</label>
				<ul class="todo-list">
					<!-- These are here just to show the structure of the list items -->
					<!-- List items should get the class `editing` when editing and `completed` when marked as completed -->
					<li :class="{'completed': item.done, 'editing': $store.state.editing == item}" v-for="item in $store.getters.getTodoList" :key="item.id">
						<div class="view">
							<input class="toggle" type="checkbox" :checked="item.done" @change="changeTodo(item.id, $event)">
							<label @dblclick="editing(item)">{{ item.title }}</label>
							<button class="destroy" @click="deleteTodo(item.id)"></button>
						</div>
						<input class="edit" :value="item.title" @keyup.enter="saveEdit($event, item.id)" @blur="saveEdit($event, item.id)" @keyup.27="cancelSave($event)">
					</li>
				</ul>
			</section>
			<!-- This footer should be hidden by default and shown when there are todos -->
			<footer class="footer"  v-show="$store.getters.getTodosLength">
				<!-- This should be `0 items left` by default -->
				<span class="todo-count"><strong>{{ $store.getters.getNoDoneLength }}</strong> item left</span>
				<!-- Remove this if you don't implement routing -->
				<ul class="filters">
					<li>
						<a :class="{'selected': $store.state.visibility == 'all'}" href="#/">All</a>
					</li>
					<li>
						<a :class="{'selected': $store.state.visibility == 'active'}" href="#/active">Active</a>
					</li>
					<li>
						<a :class="{'selected': $store.state.visibility == 'completed'}" href="#/completed">Completed</a>
					</li>
				</ul>
				<!-- Hidden if no completed items are left ↓ -->
				<button class="clear-completed" @click="removeCompleted" v-show="$store.getters.getDoneLength">Clear completed</button>
			</footer>
		</section>
		<footer class="info">
			<p>Double-click to edit a todo</p>
			<!-- Remove the below line ↓ -->
			<p>Template by <a href="http://sindresorhus.com">Sindre Sorhus</a></p>
			<!-- Change this out with your name and url ↓ -->
			<p>Created by <a href="http://todomvc.com">you</a></p>
			<p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
		</footer>
  </div>
</template>

<script>
// 安装导入相应的样式文件
import "todomvc-app-css/index.css";
import "todomvc-common/base.css";

export default {
  name: 'App',
  components: {

	},
	created() {
		// 页面刷新进来的时候,获取hash,并修改
		this.hashChange();
		// 页面之后刷新的话,动态监听hash值的变化
		window.onhashchange = this.hashChange;
	},
	updated() {
		// 存储数据
		window.localStorage.setItem("vue-todos", JSON.stringify(this.$store.state.todos));
	},
  methods: {
		// 添加todo
    addTodo(e) {
			let title = e.target.value;
			if(title.trim().length == 0){
				return;
			}
      this.$store.commit("addTodo", title);
      // 清空文本框
      e.target.value = "";
		},
		// 删除todo
		deleteTodo(id){
			this.$store.commit("deleteTodo", id);
		},
		// 修改tudo的状态
		changeTodo(id, e){
			this.$store.commit("changeTodo", {id, e});
		},
		// 编辑文本
		editing(item) {
			this.$store.commit("editing", item);
		},
		// 保存编辑
		saveEdit(e, id){
			this.$store.commit("saveEdit", {e, id});
		},
		// 取消保存
		cancelSave(e){
			this.$store.commit("cancelSave", e);
		},
		// 全选和取消全选
		changeTodoState(e){
			this.$store.commit("changeTodoState", e);
		},
		// 删除所有已经完成的项
		removeCompleted(){
			this.$store.commit("removeCompleted");
		},
		// 根据地址栏,修改store.js中state的visibity的属性
    hashChange() {
      const hash = window.location.hash.substr(1);
      if(hash == "/"){
        this.$store.commit("visibilityChange", "all");
      } else if (hash == "/active"){
				this.$store.commit("visibilityChange", "active");
			} else if (hash == "/completed"){
				this.$store.commit("visibilityChange", "completed");
			}
    }
  }
}
</script>

<style>

</style>
